import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { setScriptKey } from '@progress/kendo-licensing';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

setScriptKey('eyJhbGciOiJSUzI1NiIsInR5cCI6IlRlbGVyaWsgTGljZW5zZSBLZXkifQ.eyJ0eXBlIjoidGVsZXJpay1saWNlbnNlIiwibGljZW5zZUlkIjoiMThhOWU1MGEtYWY4My00ZDZhLWExMGItMmI3NDJiMmJlYWZhIiwidXNlcklkIjoiYmU1Mzg0YTYtMTc4My00ZjE2LWJiN2ItNGYzZGUxNmY1ZDIyIiwiaWF0IjoxNzc4NjEyMTczLCJsaWNlbnNlcyI6WyJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWxSbGJHVnlhV3NnVEdsalpXNXpaU0JGZG1sa1pXNWpaU0o5LmV5SmpiMlJsSWpvaVMwVk9SRTlWU1VGT1IxVk1RVklpTENKMGVYQmxJam9pZEhKcFlXd2lMQ0psZUhCcGNtRjBhVzl1SWpveE56Z3hNakF6TmpjNExDSjFjMlZ5U1dRaU9pSmlaVFV6T0RSaE5pMHhOemd6TFRSbU1UWXRZbUkzWWkwMFpqTmtaVEUyWmpWa01qSWlMQ0pzYVdObGJuTmxTV1FpT2lJeE9HRTVaVFV3WVMxaFpqZ3pMVFJrTm1FdFlURXdZaTB5WWpjME1tSXlZbVZoWm1FaWZRLnF0UHk0LU8wOFBKWFFiSXUzenh3R0djVE5Db05MZGthYXV3SFR2QTVoZUxWc2wtZzZDelUzamNYTnJjdUV4ekh0SFpyNzZpR0VyZEhZNjNIbXpVQlBuLWJrNDJBcjVuNE01QTVTc0gzdG8zSXcwRGoxdzF3bnh6MjNhMjBQN3ZfV1ZrUjBFZy12S3dtUmpQYldyOXBodE1EWkVqbjFvZGswb1djMHBMenByR0FGaHoybHJ3RUxMTzZKNzVaM3dnSEtJVnBfVnA5UUllTWRnb0ZlcHN4b21fYlVRRVV0RGRqT3JNVThpSHJkR3dlRkNhY0dtd0lsUFNLSW1iN1dKa1BoTnBjeDNCbXMtZF9KeFFQX1NlWFZ4VDYxX2h1ckZma2F2LWIzZGE4YjdXekpMM0szNVI4OGN3N2hkOEZfbVJ0bVg2d0FTMGRhQnFsQXFLbE5aeWg1ZyIsImV5SmhiR2NpT2lKU1V6STFOaUlzSW5SNWNDSTZJbFJsYkdWeWFXc2dUR2xqWlc1elpTQkZkbWxrWlc1alpTSjkuZXlKMGVYQmxJam9pZFhOaFoyVWlMQ0oxYzJWeVNXUWlPaUppWlRVek9EUmhOaTB4TnpnekxUUm1NVFl0WW1JM1lpMDBaak5rWlRFMlpqVmtNaklpTENKc2FXTmxibk5sU1dRaU9pSXhPR0U1WlRVd1lTMWhaamd6TFRSa05tRXRZVEV3WWkweVlqYzBNbUl5WW1WaFptRWlmUS5CVEx2UFVET3IyVW50MnZPaWRIcUFBMlk5aEZKLW9CVV8tU281cnRMVUlLS0JCOU0xNExmc3BHcU9aTzd0WnY4NGlmYlBDQWVHOUJxZU54Y2h5a3lsWWowQmMwdDQwX24xWER1dENrZ3h3bXkxM2FJbUdTU0VFdlA2RG1GN2oyWVlESVRacjBIdGh6U3JEOU9jUTdPNTJDa19NWlpJaWwzajR5bVBnSF9yV0k0X1VIZFdNeGs1UU5PdGtVMlpHWDBodGxjX3dZa0poZlFUNWRwRjJjcEVja2p3eXhNdlBXcEtEcktnOGhNWDVWRVYyRjNyc2FUajFQamstSEZQa09nOWRQVGRyM3FWbW5oM0tYSDdWS1VKZzFmQkJOTEFIc24xVG90RFZhamw0TWNNUnQ0V2Q1Sk5fMWkzYldfU3o2MU9PR2dPbnU1a2tDM2hqMFJCaUNPa0EiXSwicHJvZHVjdHMiOlt7ImNvZGUiOiJLRU5ET1VJQU5HVUxBUiIsImxpY2Vuc2VFeHBpcmF0aW9uRGF0ZSI6MTc4MTIwMzY3OCwidHJpYWwiOnRydWV9XSwiYXVkIjoidCoqKioqKioqKioqQGcqKioqLmNvbSIsImxpY2Vuc2VIb2xkZXIiOiJ0KioqKioqKioqKipAZyoqKiouY29tIiwiaW50ZWdyaXR5Ijoia2xHRS81WXMycCtRZlFIZnEvYkNSeEdkWGt1eE1BcittNG1LUzlsQ2dvMD0ifQ.k_r0sijTWBNANc0KJ0WojnNR4xPH-k9JKh-GYn4FCkKEdmpc4UcjGzEi_Ig_aPQxxCcgs3E9lp7NZhGsKnZ1LVoSqmatyVFJEYsk0lYnSDJXsJom8r5PaGMSdLIeLJeq6SC9SBHaeIkO1fRjye_3LYpDL62jjnye4TF4II-7h9NpnWBYTh5qZ5vc1JYeFZDwi7AW1baoABf-rJtFryV5ECXgGKkSJOU2GEUfQyFWYbVB1tqHFl9FxyEi72oss7RqPWZpEEy0kLBZ9ig0L8jTbJxJJ_W1nYEsyD9yYkVTwMNBQg3KNb8evShIzzZZ0UqpZlwVdmT4FxPfLHyALX5-vw');

export function getBaseUrl() {
  return document.getElementsByTagName('base')[0].href;
}

const providers = [
  { provide: 'BASE_URL', useFactory: getBaseUrl, deps: [] }
];

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic(providers).bootstrapModule(AppModule)
  .catch(err => console.log(err));
